"""SweepExecutor: runs a full experiment pipeline over all condition combinations.

A sweep is defined by an ExperimentConfig that may list multiple VAEs,
channel strategies, note-detection methods, or other axis values.  The
SweepExecutor enumerates all combinations with itertools.product, clones
the base config for each condition, runs the full pipeline, and collects
results via ExperimentTracker.

Typical usage
-------------
    executor = SweepExecutor(base_config)
    all_results = executor.run()
"""

from __future__ import annotations

import gc
import itertools
import json
import logging
import os
import tempfile
import time
from copy import deepcopy
from pathlib import Path
from typing import Any

from midi_vae.config import (
    ExperimentConfig,
    NoteDetectionConfig,
    RenderConfig,
    TrackingConfig,
    VAEConfig,
)
from midi_vae.models.vae_wrapper import FrozenImageVAE
import midi_vae.models.vae_registry  # noqa: F401 — trigger registration of all VAEs
from midi_vae.pipelines.base import PipelineRunner, PipelineStage
from midi_vae.pipelines.detect import DetectStage
from midi_vae.pipelines.encode import EncodeStage
from midi_vae.pipelines.decode import DecodeStage
from midi_vae.pipelines.evaluate import EvaluateStage
from midi_vae.pipelines.ingest import (
    DEFAULT_FILE_BATCH_SIZE,
    IngestStage,
    iter_chunks,
    iter_file_batches,
)
from midi_vae.pipelines.render import RenderStage
from midi_vae.registry import ComponentRegistry
from midi_vae.tracking.experiment import ExperimentTracker

logger = logging.getLogger(__name__)


class SweepCondition:
    """Represents a single condition (cell) in the sweep grid.

    Attributes:
        vae_cfg: The single VAEConfig for this condition.
        channel_strategy: Render channel strategy name.
        detection_method: Note-detection method name.
        detection_params: Params dict for the detection method.
        label: Human-readable label for logging.
    """

    # Relative compute cost weights by VAE model name pattern.
    # The baseline (1.0) corresponds to Stable Diffusion 1.5 / 2.1 VAEs.
    _VAE_COST_WEIGHTS: dict[str, float] = {
        "sd_1": 1.0,
        "sd_2": 1.0,
        "sdxl": 1.5,
        "sdxl_turbo": 1.5,
        "sd3": 2.0,
        "sd3.5": 2.0,
        "flux": 2.5,
        "cogview4": 2.5,
        "kandinsky": 1.2,
        "playground": 1.5,
    }

    # Relative compute cost by channel strategy.
    _CHANNEL_COST_WEIGHTS: dict[str, float] = {
        "velocity_only": 1.0,
        "vo_split": 1.1,
        "vos": 1.2,
    }

    def __init__(
        self,
        vae_cfg: VAEConfig,
        channel_strategy: str,
        detection_method: str,
        detection_params: dict[str, Any],
    ) -> None:
        self.vae_cfg = vae_cfg
        self.channel_strategy = channel_strategy
        self.detection_method = detection_method
        self.detection_params = detection_params
        self.label = (
            f"{vae_cfg.name}__{channel_strategy}__{detection_method}"
        )

    def estimated_cost(self) -> float:
        """Estimate relative compute cost for load balancing.

        Larger models (more params, higher resolution) take longer.
        The estimate is based on the VAE model name and channel strategy.

        Returns:
            A relative weight where 1.0 represents the baseline SD 1.5 cost.
            The total cost is vae_weight * channel_weight.
        """
        name_lower = self.vae_cfg.name.lower()

        # Match against known VAE name patterns (most specific first)
        vae_weight = 1.0
        for pattern, weight in self._VAE_COST_WEIGHTS.items():
            if pattern in name_lower:
                vae_weight = weight
                break

        channel_weight = self._CHANNEL_COST_WEIGHTS.get(self.channel_strategy, 1.0)
        return vae_weight * channel_weight


class SweepExecutor:
    """Runs a full encode-decode-detect-evaluate pipeline for every condition.

    Conditions are generated by taking the Cartesian product of:
      * config.vaes (each VAE becomes a separate condition)
      * sweep_strategies (channel strategies; defaults to [config.render.channel_strategy])
      * sweep_detectors (detection methods; defaults to [config.note_detection.method])

    For each condition, a modified ExperimentConfig is derived from the base
    config, an ExperimentTracker is created, and a PipelineRunner executes the
    full stage sequence.

    Args:
        config: Base experiment configuration.
        sweep_strategies: Optional list of channel strategy names to sweep.
            If None, only the strategy in the base config is used.
        sweep_detectors: Optional list of detection method names to sweep.
            If None, only the method in the base config is used.
        extra_stages: Optional list of additional pipeline stages to append
            after EvaluateStage.  Useful for custom analysis steps.
    """

    def __init__(
        self,
        config: ExperimentConfig,
        sweep_strategies: list[str] | None = None,
        sweep_detectors: list[str] | None = None,
        extra_stages: list[PipelineStage] | None = None,
    ) -> None:
        self.config = config
        self._sweep_strategies = sweep_strategies or [config.render.channel_strategy]
        self._sweep_detectors = sweep_detectors or [config.note_detection.method]
        self._extra_stages = extra_stages or []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def conditions(self) -> list[SweepCondition]:
        """Enumerate all sweep conditions from the Cartesian product.

        Returns:
            List of SweepCondition objects, one per (vae, strategy, detector) triple.
        """
        vaes = self.config.vaes
        if not vaes:
            logger.warning("SweepExecutor: no VAEs configured — returning empty sweep")
            return []

        combos = list(
            itertools.product(vaes, self._sweep_strategies, self._sweep_detectors)
        )

        return [
            SweepCondition(
                vae_cfg=vae_cfg,
                channel_strategy=strategy,
                detection_method=detector,
                detection_params=dict(self.config.note_detection.params),
            )
            for vae_cfg, strategy, detector in combos
        ]

    def run(
        self,
        resume_from: str | None = None,
        dry_run: bool = False,
        wandb_logger: Any = None,
        condition_indices: list[int] | None = None,
    ) -> dict[str, Any]:
        """Execute the sweep: one pipeline run per condition.

        Args:
            resume_from: Stage name to resume from in each pipeline.
                Passed through to PipelineRunner.run().
            dry_run: If True, only enumerate conditions and return without
                executing any pipelines.  Useful for planning / debugging.
            wandb_logger: Optional WandbLogger instance for per-condition
                metric logging.  Unused by SweepExecutor directly but accepted
                for API compatibility with callers that pass it through.
            condition_indices: If given, only the conditions at these
                zero-based indices (into the full conditions list) are run.
                All other indices are skipped.  None means run all conditions.

        Returns:
            Dict mapping condition label -> pipeline context produced by that run.
            Also includes a "__summary__" key with aggregated metrics_summary.
        """
        all_conditions = self.conditions()
        logger.info(
            "SweepExecutor: %d conditions to run", len(all_conditions)
        )

        if dry_run:
            logger.info("SweepExecutor: dry_run=True, skipping execution")
            return {
                "__conditions__": [c.label for c in all_conditions],
                "__summary__": {},
            }

        # Build the set of indices to run (None = all).
        if condition_indices is not None:
            index_set = set(condition_indices)
            logger.info(
                "SweepExecutor: running subset of %d/%d conditions (indices: %s)",
                len(index_set),
                len(all_conditions),
                sorted(index_set),
            )
        else:
            index_set = None

        all_results: dict[str, Any] = {}
        aggregated_summary: dict[str, dict[str, float]] = {}

        for i, condition in enumerate(all_conditions):
            if index_set is not None and i not in index_set:
                logger.debug("SweepExecutor: skipping condition %d — not in subset", i)
                continue
            logger.info(
                "SweepExecutor: running condition %d/%d — %s",
                i + 1,
                len(all_conditions),
                condition.label,
            )

            cond_config = self._make_condition_config(condition, i)
            tracker = ExperimentTracker(cond_config)
            context = self._run_condition(cond_config, resume_from)

            # Log per-VAE metrics summary
            summary = context.get("metrics_summary", {})
            if summary:
                tracker.log_metrics(
                    # Flatten nested dict for logging
                    {
                        f"{vae}/{k}": v
                        for vae, kv in summary.items()
                        for k, v in kv.items()
                    },
                    tag="sweep_eval",
                )
                aggregated_summary[condition.label] = {
                    k: v
                    for kv in summary.values()
                    for k, v in kv.items()
                }
                # Write relay file for distributed wandb aggregation (no-op
                # when MIDI_VAE_WANDB_RELAY_DIR is not set).
                self._write_relay(i, condition.label, summary)

            all_results[condition.label] = context

            # Free GPU memory between conditions to prevent OOM when
            # sweeping across multiple VAEs sequentially.
            self._free_gpu_memory()

        all_results["__summary__"] = aggregated_summary
        logger.info("SweepExecutor: all conditions complete")
        return all_results

    def run_subset(
        self,
        condition_indices: list[int],
        resume_from: str | None = None,
        wandb_logger: Any = None,
    ) -> dict[str, Any]:
        """Run only the conditions at the given zero-based indices.

        This is the primary entry point for distributed sweep execution: each
        worker process calls ``run_subset`` with its own slice of the global
        condition index list.

        Args:
            condition_indices: Zero-based indices into the list returned by
                :meth:`conditions`.  Indices outside the valid range are
                silently ignored.
            resume_from: Stage name to resume from (passed through to the
                underlying :meth:`run` call).
            wandb_logger: Optional WandbLogger for per-condition metric logging.

        Returns:
            Same structure as :meth:`run` but only containing entries for the
            requested conditions.
        """
        return self.run(
            resume_from=resume_from,
            dry_run=False,
            wandb_logger=wandb_logger,
            condition_indices=condition_indices,
        )

    @staticmethod
    def _free_gpu_memory() -> None:
        """Release cached GPU memory between sweep conditions.

        Calls gc.collect() to trigger Python garbage collection of any
        lingering VAE model objects, then clears the PyTorch CUDA cache.
        Safe to call on CPU-only machines.
        """
        gc.collect()
        try:
            import torch
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
        except ImportError:
            pass

    def _write_relay(
        self,
        condition_index: int,
        label: str,
        summary: dict[str, Any],
    ) -> None:
        """Write a metric relay JSON for the distributed wandb watcher.

        Writes a small JSON file to the shared relay directory so that rank 0's
        :class:`~midi_vae.tracking.wandb_relay.WandbRelayWatcher` can pick it
        up and forward the metrics to the single wandb run.

        This method is a no-op unless the environment variable
        ``MIDI_VAE_WANDB_RELAY_DIR`` is set (i.e. we are in distributed mode).

        The file is written atomically: it is first written to a temporary file
        in the same directory and then renamed, so the watcher never sees a
        partial write.

        Args:
            condition_index: Zero-based index of this condition in the global
                sweep (used to form a unique, sortable filename).
            label: Human-readable condition label (e.g.
                ``"sd15__velocity_only__threshold"``).
            summary: Nested ``{vae_name: {metric_name: value}}`` dict as
                produced by :meth:`run`.
        """
        relay_dir_str = os.environ.get("MIDI_VAE_WANDB_RELAY_DIR")
        if not relay_dir_str:
            return

        relay_dir = Path(relay_dir_str)
        relay_dir.mkdir(parents=True, exist_ok=True)

        rank = int(os.environ.get("SLURM_PROCID", "0"))
        relay_file = relay_dir / f"cond_{condition_index:04d}_rank{rank:04d}.json"

        relay_data: dict[str, Any] = {
            "condition_index": condition_index,
            "condition_label": label,
            "rank": rank,
            "timestamp": time.time(),
            "metrics_summary": summary,
        }

        # Atomic write: write to a temp file then rename so the watcher
        # never observes a partial file.
        try:
            tmp_fd, tmp_path = tempfile.mkstemp(dir=str(relay_dir), suffix=".tmp")
            with os.fdopen(tmp_fd, "w") as fh:
                json.dump(relay_data, fh, default=str)
            Path(tmp_path).rename(relay_file)
            logger.debug(
                "_write_relay: wrote relay file %s (rank %d)", relay_file.name, rank
            )
        except Exception as exc:
            logger.warning(
                "_write_relay: failed to write %s: %s", relay_file, exc
            )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _make_condition_config(
        self, condition: SweepCondition, index: int
    ) -> ExperimentConfig:
        """Build a single-VAE ExperimentConfig for a sweep condition.

        Creates a copy of the base config with:
          * vaes = [condition.vae_cfg]
          * render.channel_strategy = condition.channel_strategy
          * note_detection = condition.detection_method / params
          * tracking.experiment_name tagged with the condition label

        Args:
            condition: The sweep condition.
            index: Zero-based index of this condition (used in experiment name).

        Returns:
            A new ExperimentConfig for this condition.
        """
        base = self.config

        new_render = RenderConfig(
            channel_strategy=condition.channel_strategy,
            pitch_axis=base.render.pitch_axis,
            normalize_range=base.render.normalize_range,
            resize_method=base.render.resize_method,
        )

        new_detection = NoteDetectionConfig(
            method=condition.detection_method,
            params=condition.detection_params,
        )

        safe_label = condition.label.replace("/", "_").replace(" ", "_")
        new_tracking = TrackingConfig(
            experiment_name=f"{base.tracking.experiment_name}__cond{index:04d}__{safe_label}",
            wandb_enabled=base.tracking.wandb_enabled,
            wandb_project=base.tracking.wandb_project,
            wandb_entity=base.tracking.wandb_entity,
            wandb_mode=base.tracking.wandb_mode,
            wandb_dir=base.tracking.wandb_dir,
            wandb_tags=list(base.tracking.wandb_tags),
            save_reconstructions=base.tracking.save_reconstructions,
            save_latents=base.tracking.save_latents,
            checkpoint_every_n=base.tracking.checkpoint_every_n,
        )

        return ExperimentConfig(
            paths=base.paths,
            data=base.data,
            render=new_render,
            vaes=[condition.vae_cfg],
            note_detection=new_detection,
            sublatent=base.sublatent,
            metrics=base.metrics,
            tracking=new_tracking,
            seed=base.seed,
            device=base.device,
            num_workers=base.num_workers,
        )

    def _build_stages(self, config: ExperimentConfig) -> list[PipelineStage]:
        """Instantiate the standard pipeline stage sequence.

        Args:
            config: The per-condition experiment config.

        Returns:
            Ordered list of PipelineStage instances.
        """
        stages: list[PipelineStage] = [
            IngestStage(config),
            RenderStage(config),
            EncodeStage(config),
            DecodeStage(config),
            DetectStage(config),
            EvaluateStage(config),
        ]
        stages.extend(self._extra_stages)
        return stages

    def _run_condition(
        self,
        config: ExperimentConfig,
        resume_from: str | None,
    ) -> dict[str, Any]:
        """Run the full pipeline for a single condition.

        When ``config.data.pipeline_chunk_size`` is positive, bars are
        processed in chunks to avoid materialising all images, latents, and
        reconstructed images in memory simultaneously.  The IngestStage runs
        once to produce all BarData objects (lightweight), then the rest of the
        pipeline (Render → Encode → Decode → Detect → Evaluate) is executed
        repeatedly on successive slices of that list.  Per-bar metric dicts are
        accumulated across chunks and a final summary is computed after all
        chunks have been processed.

        When ``pipeline_chunk_size`` is 0 or negative the original
        single-pass behaviour is preserved.

        Args:
            config: Per-condition experiment config.
            resume_from: Stage name to resume from (or None).

        Returns:
            Final pipeline context dict containing at least "bars",
            "metrics", and "metrics_summary".  Heavy tensor keys
            ("images", "latents", "recon_images", "reconstructed_bars")
            are NOT present in the returned context when chunking is active
            — they are freed after each chunk.
        """
        cache_dir = str(
            Path(config.paths.cache_dir) / config.tracking.experiment_name
        )
        chunk_size: int = config.data.pipeline_chunk_size

        # ------------------------------------------------------------------ #
        # Fast path: no chunking requested — run the original single pass.    #
        # ------------------------------------------------------------------ #
        if chunk_size <= 0:
            stages = self._build_stages(config)
            runner = PipelineRunner(stages, config, cache_dir=cache_dir)
            return runner.run(resume_from=resume_from)

        # ------------------------------------------------------------------ #
        # Chunked path — streaming ingestion                                  #
        # ------------------------------------------------------------------ #
        # Instead of loading ALL bars into memory at once (which OOMs on
        # large datasets like full Lakh), we:
        #   1. Resolve the file list (cheap — just paths).
        #   2. Iterate over file batches (e.g. 100 files at a time).
        #   3. For each file batch, ingest bars → run pipeline → discard bars.
        # This keeps peak memory proportional to one file batch, not the
        # entire dataset.

        ingest_stage = IngestStage(config)
        all_files = ingest_stage.resolve_files()

        if not all_files:
            logger.warning("_run_condition: no files found — skipping")
            return {"bars": [], "metrics": {}, "metrics_summary": {}}

        num_workers: int = getattr(config, "num_workers", 1)
        ingestor = ingest_stage.make_ingestor()

        file_batch_size = getattr(
            config.data, "file_batch_size", None
        ) or DEFAULT_FILE_BATCH_SIZE
        n_file_batches = (len(all_files) + file_batch_size - 1) // file_batch_size

        logger.info(
            "_run_condition: %d files, streaming in %d file-batch(es) of up to %d",
            len(all_files),
            n_file_batches,
            file_batch_size,
        )

        # ------------------------------------------------------------------
        # Pre-load VAE instances once — avoids reloading weights per chunk.
        # ------------------------------------------------------------------
        vae_instances: dict[str, FrozenImageVAE] = {}
        for vae_cfg in config.vaes:
            try:
                vae_cls = ComponentRegistry.get("vae", vae_cfg.name)
                vae = vae_cls(vae_cfg, device=config.device)
                vae.ensure_loaded()
                vae_instances[vae_cfg.name] = vae
                logger.info("_run_condition: pre-loaded VAE '%s'", vae_cfg.name)
            except Exception as exc:
                logger.warning(
                    "_run_condition: failed to pre-load VAE '%s': %s", vae_cfg.name, exc
                )

        # ------------------------------------------------------------------
        # Instantiate chunk stages once — stateless stages are safe to reuse.
        # ------------------------------------------------------------------
        chunk_stages: list[PipelineStage] = [
            RenderStage(config),
            EncodeStage(config),
            DecodeStage(config),
            DetectStage(config),
            EvaluateStage(config),
        ]
        chunk_stages.extend(self._extra_stages)

        chunk_runner = PipelineRunner(
            chunk_stages, config, cache_dir=None  # no caching for chunks
        )
        if chunk_runner._execution_order is None:
            chunk_runner._execution_order = chunk_runner._topological_sort()

        # Accumulators: per-VAE list of per-bar metric dicts.
        accumulated_metrics: dict[str, list[dict[str, float]]] = {}
        total_bars_processed = 0
        pipeline_chunk_idx = 0

        for fb_idx, file_batch in enumerate(
            iter_file_batches(all_files, file_batch_size)
        ):
            # --- Ingest this batch of files ---
            logger.info(
                "Ingesting file batch %d/%d (%d files)",
                fb_idx + 1, n_file_batches, len(file_batch),
            )
            batch_bars = ingest_stage.ingest_batch(
                file_batch, ingestor=ingestor, num_workers=num_workers
            )

            if not batch_bars:
                logger.info("File batch %d/%d produced 0 bars, skipping", fb_idx + 1, n_file_batches)
                continue

            total_bars_processed += len(batch_bars)

            # --- Sub-chunk the batch bars through the pipeline ---
            # If pipeline_chunk_size is set, process in smaller slices.
            # Otherwise process the entire file batch at once.
            for chunk_bars in iter_chunks(batch_bars, chunk_size):
                pipeline_chunk_idx += 1
                logger.info(
                    "Processing pipeline chunk %d (file batch %d/%d, %d bars)",
                    pipeline_chunk_idx, fb_idx + 1, n_file_batches, len(chunk_bars),
                )

                chunk_context: dict[str, Any] = {
                    "bars": chunk_bars,
                    "_vae_instances": vae_instances,
                }

                for stage in chunk_runner._execution_order:
                    stage_name = stage.name
                    logger.info("[RUN chunk %d] %s", pipeline_chunk_idx, stage_name)
                    t0 = time.time()
                    outputs = stage.run(chunk_context)
                    elapsed = time.time() - t0
                    logger.info(
                        "[DONE chunk %d] %s (%.1fs)",
                        pipeline_chunk_idx, stage_name, elapsed,
                    )
                    chunk_context.update(outputs)

                # Accumulate per-bar metrics from this chunk.
                chunk_metrics: dict[str, list[dict[str, float]]] = chunk_context.get(
                    "metrics", {}
                )
                for vae_name, bar_dicts in chunk_metrics.items():
                    accumulated_metrics.setdefault(vae_name, []).extend(bar_dicts)

                # Release heavy tensor data before the next chunk.
                for heavy_key in ("images", "latents", "recon_images", "reconstructed_bars"):
                    chunk_context.pop(heavy_key, None)
                del chunk_context
                gc.collect()

            # Release the batch bars before ingesting the next file batch.
            del batch_bars
            gc.collect()

        # After all file batches complete, release VAE instances.
        del vae_instances
        self._free_gpu_memory()

        # ------------------------------------------------------------------ #
        # Aggregate accumulated per-bar metrics into a final summary.         #
        # ------------------------------------------------------------------ #
        final_metrics_summary: dict[str, dict[str, float]] = {}
        for vae_name, bar_dicts in accumulated_metrics.items():
            if bar_dicts:
                all_keys: set[str] = set().union(*[d.keys() for d in bar_dicts])  # type: ignore[arg-type]
                summary: dict[str, float] = {}
                for key in all_keys:
                    values = [d[key] for d in bar_dicts if key in d]
                    summary[key] = sum(values) / len(values) if values else float("nan")
                final_metrics_summary[vae_name] = summary
            else:
                final_metrics_summary[vae_name] = {}

        logger.info(
            "_run_condition: streaming processing complete — %d VAEs evaluated over %d total bars",
            len(final_metrics_summary),
            total_bars_processed,
        )

        return {
            "bars": [],  # Don't hold all bars in final result — they've been streamed
            "metrics": accumulated_metrics,
            "metrics_summary": final_metrics_summary,
        }
