"""SweepExecutor: runs a full experiment pipeline over all condition combinations.

A sweep is defined by an ExperimentConfig that may list multiple VAEs,
channel strategies, note-detection methods, or other axis values.  The
SweepExecutor enumerates all combinations with itertools.product, clones
the base config for each condition, runs the full pipeline, and collects
results via ExperimentTracker.

Typical usage
-------------
    executor = SweepExecutor(base_config)
    all_results = executor.run()
"""

from __future__ import annotations

import gc
import itertools
import logging
import time
from copy import deepcopy
from pathlib import Path
from typing import Any

from midi_vae.config import (
    ExperimentConfig,
    NoteDetectionConfig,
    RenderConfig,
    TrackingConfig,
    VAEConfig,
)
from midi_vae.pipelines.base import PipelineRunner, PipelineStage
from midi_vae.pipelines.detect import DetectStage
from midi_vae.pipelines.encode import EncodeStage
from midi_vae.pipelines.decode import DecodeStage
from midi_vae.pipelines.evaluate import EvaluateStage
from midi_vae.pipelines.ingest import IngestStage
from midi_vae.pipelines.render import RenderStage
from midi_vae.tracking.experiment import ExperimentTracker

logger = logging.getLogger(__name__)


class SweepCondition:
    """Represents a single condition (cell) in the sweep grid.

    Attributes:
        vae_cfg: The single VAEConfig for this condition.
        channel_strategy: Render channel strategy name.
        detection_method: Note-detection method name.
        detection_params: Params dict for the detection method.
        label: Human-readable label for logging.
    """

    def __init__(
        self,
        vae_cfg: VAEConfig,
        channel_strategy: str,
        detection_method: str,
        detection_params: dict[str, Any],
    ) -> None:
        self.vae_cfg = vae_cfg
        self.channel_strategy = channel_strategy
        self.detection_method = detection_method
        self.detection_params = detection_params
        self.label = (
            f"{vae_cfg.name}__{channel_strategy}__{detection_method}"
        )


class SweepExecutor:
    """Runs a full encode-decode-detect-evaluate pipeline for every condition.

    Conditions are generated by taking the Cartesian product of:
      * config.vaes (each VAE becomes a separate condition)
      * sweep_strategies (channel strategies; defaults to [config.render.channel_strategy])
      * sweep_detectors (detection methods; defaults to [config.note_detection.method])

    For each condition, a modified ExperimentConfig is derived from the base
    config, an ExperimentTracker is created, and a PipelineRunner executes the
    full stage sequence.

    Args:
        config: Base experiment configuration.
        sweep_strategies: Optional list of channel strategy names to sweep.
            If None, only the strategy in the base config is used.
        sweep_detectors: Optional list of detection method names to sweep.
            If None, only the method in the base config is used.
        extra_stages: Optional list of additional pipeline stages to append
            after EvaluateStage.  Useful for custom analysis steps.
    """

    def __init__(
        self,
        config: ExperimentConfig,
        sweep_strategies: list[str] | None = None,
        sweep_detectors: list[str] | None = None,
        extra_stages: list[PipelineStage] | None = None,
    ) -> None:
        self.config = config
        self._sweep_strategies = sweep_strategies or [config.render.channel_strategy]
        self._sweep_detectors = sweep_detectors or [config.note_detection.method]
        self._extra_stages = extra_stages or []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def conditions(self) -> list[SweepCondition]:
        """Enumerate all sweep conditions from the Cartesian product.

        Returns:
            List of SweepCondition objects, one per (vae, strategy, detector) triple.
        """
        vaes = self.config.vaes
        if not vaes:
            logger.warning("SweepExecutor: no VAEs configured — returning empty sweep")
            return []

        combos = list(
            itertools.product(vaes, self._sweep_strategies, self._sweep_detectors)
        )

        return [
            SweepCondition(
                vae_cfg=vae_cfg,
                channel_strategy=strategy,
                detection_method=detector,
                detection_params=dict(self.config.note_detection.params),
            )
            for vae_cfg, strategy, detector in combos
        ]

    def run(
        self,
        resume_from: str | None = None,
        dry_run: bool = False,
    ) -> dict[str, Any]:
        """Execute the sweep: one pipeline run per condition.

        Args:
            resume_from: Stage name to resume from in each pipeline.
                Passed through to PipelineRunner.run().
            dry_run: If True, only enumerate conditions and return without
                executing any pipelines.  Useful for planning / debugging.

        Returns:
            Dict mapping condition label -> pipeline context produced by that run.
            Also includes a "__summary__" key with aggregated metrics_summary.
        """
        all_conditions = self.conditions()
        logger.info(
            "SweepExecutor: %d conditions to run", len(all_conditions)
        )

        if dry_run:
            logger.info("SweepExecutor: dry_run=True, skipping execution")
            return {
                "__conditions__": [c.label for c in all_conditions],
                "__summary__": {},
            }

        all_results: dict[str, Any] = {}
        aggregated_summary: dict[str, dict[str, float]] = {}

        for i, condition in enumerate(all_conditions):
            logger.info(
                "SweepExecutor: running condition %d/%d — %s",
                i + 1,
                len(all_conditions),
                condition.label,
            )

            cond_config = self._make_condition_config(condition, i)
            tracker = ExperimentTracker(cond_config)
            context = self._run_condition(cond_config, resume_from)

            # Log per-VAE metrics summary
            summary = context.get("metrics_summary", {})
            if summary:
                tracker.log_metrics(
                    # Flatten nested dict for logging
                    {
                        f"{vae}/{k}": v
                        for vae, kv in summary.items()
                        for k, v in kv.items()
                    },
                    tag="sweep_eval",
                )
                aggregated_summary[condition.label] = {
                    k: v
                    for kv in summary.values()
                    for k, v in kv.items()
                }

            all_results[condition.label] = context

            # Free GPU memory between conditions to prevent OOM when
            # sweeping across multiple VAEs sequentially.
            self._free_gpu_memory()

        all_results["__summary__"] = aggregated_summary
        logger.info("SweepExecutor: all conditions complete")
        return all_results

    @staticmethod
    def _free_gpu_memory() -> None:
        """Release cached GPU memory between sweep conditions.

        Calls gc.collect() to trigger Python garbage collection of any
        lingering VAE model objects, then clears the PyTorch CUDA cache.
        Safe to call on CPU-only machines.
        """
        gc.collect()
        try:
            import torch
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
        except ImportError:
            pass

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _make_condition_config(
        self, condition: SweepCondition, index: int
    ) -> ExperimentConfig:
        """Build a single-VAE ExperimentConfig for a sweep condition.

        Creates a copy of the base config with:
          * vaes = [condition.vae_cfg]
          * render.channel_strategy = condition.channel_strategy
          * note_detection = condition.detection_method / params
          * tracking.experiment_name tagged with the condition label

        Args:
            condition: The sweep condition.
            index: Zero-based index of this condition (used in experiment name).

        Returns:
            A new ExperimentConfig for this condition.
        """
        base = self.config

        new_render = RenderConfig(
            channel_strategy=condition.channel_strategy,
            pitch_axis=base.render.pitch_axis,
            normalize_range=base.render.normalize_range,
            resize_method=base.render.resize_method,
        )

        new_detection = NoteDetectionConfig(
            method=condition.detection_method,
            params=condition.detection_params,
        )

        safe_label = condition.label.replace("/", "_").replace(" ", "_")
        new_tracking = TrackingConfig(
            experiment_name=f"{base.tracking.experiment_name}__cond{index:04d}__{safe_label}",
            wandb_enabled=base.tracking.wandb_enabled,
            wandb_project=base.tracking.wandb_project,
            wandb_entity=base.tracking.wandb_entity,
            wandb_mode=base.tracking.wandb_mode,
            wandb_dir=base.tracking.wandb_dir,
            wandb_tags=list(base.tracking.wandb_tags),
            save_reconstructions=base.tracking.save_reconstructions,
            save_latents=base.tracking.save_latents,
            checkpoint_every_n=base.tracking.checkpoint_every_n,
        )

        return ExperimentConfig(
            paths=base.paths,
            data=base.data,
            render=new_render,
            vaes=[condition.vae_cfg],
            note_detection=new_detection,
            sublatent=base.sublatent,
            metrics=base.metrics,
            tracking=new_tracking,
            seed=base.seed,
            device=base.device,
            num_workers=base.num_workers,
        )

    def _build_stages(self, config: ExperimentConfig) -> list[PipelineStage]:
        """Instantiate the standard pipeline stage sequence.

        Args:
            config: The per-condition experiment config.

        Returns:
            Ordered list of PipelineStage instances.
        """
        stages: list[PipelineStage] = [
            IngestStage(config),
            RenderStage(config),
            EncodeStage(config),
            DecodeStage(config),
            DetectStage(config),
            EvaluateStage(config),
        ]
        stages.extend(self._extra_stages)
        return stages

    def _run_condition(
        self,
        config: ExperimentConfig,
        resume_from: str | None,
    ) -> dict[str, Any]:
        """Run the full pipeline for a single condition.

        When ``config.data.pipeline_chunk_size`` is positive, bars are
        processed in chunks to avoid materialising all images, latents, and
        reconstructed images in memory simultaneously.  The IngestStage runs
        once to produce all BarData objects (lightweight), then the rest of the
        pipeline (Render → Encode → Decode → Detect → Evaluate) is executed
        repeatedly on successive slices of that list.  Per-bar metric dicts are
        accumulated across chunks and a final summary is computed after all
        chunks have been processed.

        When ``pipeline_chunk_size`` is 0 or negative the original
        single-pass behaviour is preserved.

        Args:
            config: Per-condition experiment config.
            resume_from: Stage name to resume from (or None).

        Returns:
            Final pipeline context dict containing at least "bars",
            "metrics", and "metrics_summary".  Heavy tensor keys
            ("images", "latents", "recon_images", "reconstructed_bars")
            are NOT present in the returned context when chunking is active
            — they are freed after each chunk.
        """
        cache_dir = str(
            Path(config.paths.cache_dir) / config.tracking.experiment_name
        )
        chunk_size: int = config.data.pipeline_chunk_size

        # ------------------------------------------------------------------ #
        # Fast path: no chunking requested — run the original single pass.    #
        # ------------------------------------------------------------------ #
        if chunk_size <= 0:
            stages = self._build_stages(config)
            runner = PipelineRunner(stages, config, cache_dir=cache_dir)
            return runner.run(resume_from=resume_from)

        # ------------------------------------------------------------------ #
        # Chunked path                                                         #
        # ------------------------------------------------------------------ #

        # Step 1: Ingest once — BarData objects are lightweight (~12 KB each).
        ingest_stage = IngestStage(config)
        ingest_runner = PipelineRunner(
            [ingest_stage], config, cache_dir=cache_dir
        )
        ingest_context = ingest_runner.run(resume_from=resume_from)
        all_bars: list[Any] = ingest_context.get("bars", [])

        if not all_bars:
            logger.warning("_run_condition: IngestStage produced no bars — skipping chunked processing")
            return ingest_context

        total_bars = len(all_bars)
        n_chunks = (total_bars + chunk_size - 1) // chunk_size
        logger.info(
            "_run_condition: %d bars split into %d chunk(s) of up to %d",
            total_bars,
            n_chunks,
            chunk_size,
        )

        # Stages that run on each chunk (excludes IngestStage).
        chunk_stage_classes = [
            RenderStage,
            EncodeStage,
            DecodeStage,
            DetectStage,
            EvaluateStage,
        ]
        chunk_stage_classes.extend(type(s) for s in self._extra_stages)

        # Accumulators: per-VAE list of per-bar metric dicts.
        accumulated_metrics: dict[str, list[dict[str, float]]] = {}

        # Collect a few example (GT, recon) pairs for visualization before
        # they are freed from each chunk context.
        max_visual_examples = 4
        # vae_name -> [(bar_id, gt_tensor, recon_tensor, channel_strategy), ...]
        visual_examples: dict[str, list[tuple[str, Any, Any, str]]] = {}

        for chunk_idx in range(n_chunks):
            start = chunk_idx * chunk_size
            end = min(start + chunk_size, total_bars)
            chunk_bars = all_bars[start:end]

            logger.info(
                "Processing chunk %d/%d (bars %d-%d)",
                chunk_idx + 1,
                n_chunks,
                start + 1,
                end,
            )

            # Build a fresh context seeded with this chunk's bars.
            chunk_context: dict[str, Any] = {"bars": chunk_bars}

            # Instantiate fresh stage objects for each chunk so that any
            # internal state (e.g. lazy-built detector) does not leak
            # across chunks.
            chunk_stages: list[PipelineStage] = [
                cls(config) for cls in chunk_stage_classes
            ]

            chunk_runner = PipelineRunner(
                chunk_stages, config, cache_dir=None  # no caching for chunks
            )

            # Run only the non-ingest stages; ingest output is already in
            # chunk_context so we skip IngestStage by not including it.
            if chunk_runner._execution_order is None:
                chunk_runner._execution_order = chunk_runner._topological_sort()

            for stage in chunk_runner._execution_order:
                stage_name = stage.name
                logger.info("[RUN chunk %d/%d] %s", chunk_idx + 1, n_chunks, stage_name)
                t0 = time.time()
                outputs = stage.run(chunk_context)
                elapsed = time.time() - t0
                logger.info(
                    "[DONE chunk %d/%d] %s (%.1fs)",
                    chunk_idx + 1, n_chunks, stage_name, elapsed,
                )
                chunk_context.update(outputs)

            # Accumulate per-bar metrics from this chunk.
            chunk_metrics: dict[str, list[dict[str, float]]] = chunk_context.get(
                "metrics", {}
            )
            for vae_name, bar_dicts in chunk_metrics.items():
                accumulated_metrics.setdefault(vae_name, []).extend(bar_dicts)

            # Collect visual examples from this chunk before the heavy keys
            # are freed.  Only gather up to max_visual_examples per VAE and
            # only until every known VAE is saturated.
            chunk_images: list[Any] = chunk_context.get("images", [])
            chunk_recons: dict[str, list[Any]] = chunk_context.get("reconstructed_bars", {})
            if chunk_images and chunk_recons:
                gt_lookup = {img.bar_id: img for img in chunk_images}
                for vae_name, recon_list in chunk_recons.items():
                    existing = visual_examples.setdefault(vae_name, [])
                    if len(existing) >= max_visual_examples:
                        continue
                    for recon in recon_list:
                        if len(existing) >= max_visual_examples:
                            break
                        gt_img = gt_lookup.get(recon.bar_id)
                        if gt_img is None:
                            continue
                        # Clone tensors so they survive after chunk_context is freed.
                        existing.append((
                            recon.bar_id,
                            gt_img.image.clone(),
                            recon.recon_image.clone(),
                            gt_img.channel_strategy,
                        ))

            # Explicitly release heavy tensor data so Python/CUDA can GC them
            # before the next chunk is rendered.
            for heavy_key in ("images", "latents", "recon_images", "reconstructed_bars", "_vae_instances"):
                chunk_context.pop(heavy_key, None)
            del chunk_context
            gc.collect()
            self._free_gpu_memory()

        # ------------------------------------------------------------------ #
        # Aggregate accumulated per-bar metrics into a final summary.         #
        # ------------------------------------------------------------------ #
        final_metrics_summary: dict[str, dict[str, float]] = {}
        for vae_name, bar_dicts in accumulated_metrics.items():
            if bar_dicts:
                all_keys: set[str] = set().union(*[d.keys() for d in bar_dicts])  # type: ignore[arg-type]
                summary: dict[str, float] = {}
                for key in all_keys:
                    values = [d[key] for d in bar_dicts if key in d]
                    summary[key] = sum(values) / len(values) if values else float("nan")
                final_metrics_summary[vae_name] = summary
            else:
                final_metrics_summary[vae_name] = {}

        logger.info(
            "_run_condition: chunked processing complete — %d VAEs evaluated over %d total bars",
            len(final_metrics_summary),
            total_bars,
        )

        return {
            "bars": all_bars,
            "metrics": accumulated_metrics,
            "metrics_summary": final_metrics_summary,
            "_visual_examples": visual_examples,
        }
